config/routes.rb
Rails.application.routes.draw do

  root to: 'short_urls#index'
  resources :short_urls, only: [:new, :index, :create], param: :url do
    collection do
      get 'upload_urls'
      get 'show'
      post 'create_uploaded_urls'
    end
  end

  namespace 'v1' do
    resources :short_url, param: :url, defaults: {format: :json}, only: [:index, :create]
    get 'shortened_url' => 'short_url#show'
    delete 'shortened_url' => 'short_url#destroy'
  end

  get '*url', to: 'short_urls#original_url'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/url_datum.rb
class UrlDatum < ApplicationRecord
  serialize :original_urls, Array

  validates_presence_of :original_urls, :mapped_url
  validates_presence_of :shortened_url, on: :update
  validates_uniqueness_of :mapped_url, :shortened_url
  after_create :set_shortened_url

  CHAR_MAPPING = {}

  (('a'..'z').to_a + ('A'..'Z').to_a + (0..9).map(&:to_s)).each_with_index {|c, i| CHAR_MAPPING[i] = c}

  def self.generate(url)
    if url_datum = get_url_datum(url)
      url_datum.add_url url
      url_datum
    else
      url_datum = UrlDatum.new(original_urls: [url])
      url_datum.set_mapped_url
      url_datum.save!
      url_datum
    end
  end

  def self.get_url_datum(url)
    find_by(mapped_url: get_mapped_url(url))
  end

  def self.generate_shortened_url number
    number += 100000 # for making shortened_url atleast 3 characters
    digits = []
    while number > 0
      remainder = number % base_length
      digits.push CHAR_MAPPING[remainder]
      number /= base_length
    end
    digits.reverse.join
  end

  def self.get_mapped_url url
    mapped_url = url.dup
    mapped_url.gsub!(/\Ahttps?:\/\//, '')
    mapped_url.gsub!(/\Awww\./, '')
    mapped_url
  end

  def set_mapped_url
    # based on id
    self.mapped_url = self.class.get_mapped_url(original_urls.first)
  end

  def add_url url
    return false unless mapped_url == self.class.get_mapped_url(url)
    return true if original_urls.include?(url)
    update_attribute(:original_urls, original_urls.push(url))
  end

  def url
    original_urls[0]
  end

  private

  def self.base_length
    @base_length ||= CHAR_MAPPING.keys.length
  end

  def set_shortened_url
    self.update_attribute(:shortened_url, self.class.generate_shortened_url(self.id))
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/short_urls_controller.rb
class ShortUrlsController < ApplicationController
  require 'csv'
  def new
    @url_datum = UrlDatum.new
  end

  def index
    @url_data = UrlDatum.all
  end

  def create
    @url_datum = UrlDatum.generate(url_params[:url])
    flash['notice'] = 'Created Short Url'
    redirect_to action: :show, url: @url_datum.mapped_url
  end

  def upload_urls
    @url_datum = UrlDatum.new
  end

  def show
    @url_datum = UrlDatum.get_url_datum(params[:url])
  end

  def original_url
    url_datum = UrlDatum.find_by(shortened_url: params[:url])
    redirect_to 'http://' + url_datum.mapped_url
  end

  def create_uploaded_urls
    transaction_successful = false
    ActiveRecord::Base.transaction do
      CSV.foreach(params[:short_url][:csv_file].path) do |row|
        UrlDatum.generate(row[0])
      end
      transaction_successful = true
    end
    if transaction_successful
      redirect_to :root, notice: 'Urls Successfully Created.'
    else
      redirect_to :root, alert: 'Upload a valid CSV file'
    end
  end

  private
  def url_params
    params.require(:url_datum).permit(:url)
  end
end

app/controllers/v1/base_controller.rb
class V1::BaseController < ApplicationController
  skip_before_action :verify_authenticity_token
end

app/controllers/v1/short_url_controller.rb
class V1::ShortUrlController < V1::BaseController
  before_action :set_url_datum, only: [:show, :destroy]
  def create
    @url_datum = UrlDatum.generate(params[:url])
    render :show, status: 201
  end

  def show
    puts "------------#{@url_datum.inspect}"
  end

  def index
    @url_data = UrlDatum.all
  end

  def destroy
    @url_datum.destroy
    render json: {}, status: 204
  end

  private
  def set_url_datum
    mapped_url = UrlDatum.get_mapped_url params[:url]
    @url_datum = UrlDatum.find_by(mapped_url: mapped_url)
    @url_datum ||= UrlDatum.find_by(shortened_url: params[:url])
    if @url_datum.nil?
      render json: {message: 'Bad Request'}, status: 400
      return
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/short_urls_helper.rb
module ShortUrlsHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title UrlShortner
    %meta{:charset => "utf-8"}/
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    %script{:src => "https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"}
    %link{:href => "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css", :rel => "stylesheet"}/
    %script{:src => "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"}
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    .container
      .flash
        - if flash[:notice]
          .alert.alert-info
            =flash[:notice]
        - if flash[:alert]
          .alert.alert-warning
            =flash[:alert]
      = yield

app/views/short_urls/index.html.haml
%h2 List of Shortened Urls
=link_to 'New', new_short_url_path, class: 'btn btn-link'
=link_to 'Upload CSV', upload_urls_short_urls_path, class: 'btn btn-link'

%table.table.table-striped
  %thead
    %tr
      %th Added Urls
      %th Shortened Url
  %tbody
    -@url_data.each do |url_datum|
      %tr
        %td
          .list-group
            -url_datum.original_urls.each do |url|
              %a{href: 'http://'+url_datum.mapped_url}= url
              |
        %td
          %a{href: '/' + url_datum.shortened_url}= url_datum.shortened_url

app/views/short_urls/new.html.haml
%br
%br
= form_for(@url_datum, url: '/short_urls', html: {class: 'form form-horizontal'}) do |f|
  - if @url_datum.errors.any?
    #error_explanation
      %h2
        = pluralize(@url_datum.errors.count, "error")
        prohibited this URL from being saved:
      %ul
        - @url_datum.errors.full_messages.each do |msg|
          %li= msg
  .field.form-group
    = f.label :URL, class: 'control-label col-sm-2 col-md-2 col-md-offset-1'
    .col-sm-10.col-md-5
      = f.text_field :url, class: 'form-control'

  .form-group
    .col-sm-offset-2.col-sm-10.col-md-offset-3
      = f.submit 'Generate', class: 'btn btn-primary'

app/views/short_urls/show.html.haml
%br
=link_to 'Home', root_path
%table.table.table-striped
  %thead
    %tr
      %th Added Urls
      %th Shortened Url
  %tbody
    %tr
      %td
        .list-group
          -@url_datum.original_urls.each do |url|
            %a{href: 'http://'+@url_datum.mapped_url}= url
      %td
        %a{href: '/' + @url_datum.shortened_url}= @url_datum.shortened_url

app/views/short_urls/upload_urls.html.haml
%h2 Upload CSV
%br
%br
= form_tag(create_uploaded_urls_short_urls_path, multipart: true, class: 'form form-horizontal') do |f|
  .field.form-group
    = label_tag :upload_csv, 'Upload CSV', class: 'control-label col-sm-2 col-md-2 col-md-offset-1'
    .col-sm-10.col-md-5
      = file_field :short_url, :csv_file, required: true, class: 'form-control'
  %br
  %br
  .form-group
    .col-sm-offset-2.col-sm-10.col-md-offset-3
      = submit_tag 'Upload', class: 'btn btn-primary'